trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/piwebapi_samples/CommonAPIActions/AngularJS'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/piwebapi_samples/CommonAPIActions/AngularJS'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/piwebapi_samples/CommonAPIActions/AngularJS'
  - name: CredFile
    value: test-config.js
  - name: CredFileLibrary
    value: product-readiness.piwebapi_angularjs.js
  - name: analysisProject
    value: PIWebAPI_AngularJS

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - template: '/piwebapi_samples/CommonAPIActions/AngularJS/run-tests.yml'
        parameters:
          projectPath: $(Build.SourcesDirectory)$(projPath)

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: nodejs
      web: true
