// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "Only passed queries from tests.", Scope = "member", Target = "~M:OSIsoft.PISystemDeploymentTests.PISqlClientTests.ElementQueryTest(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "Only passed queries from tests.", Scope = "member", Target = "~M:OSIsoft.PISystemDeploymentTests.PISqlClientTests.ElementAttributeQueryTest(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "Only passed queries from tests.", Scope = "member", Target = "~M:OSIsoft.PISystemDeploymentTests.PISqlClientTests.ExecuteQuery(System.String,System.Int32,System.Int32)~System.Data.DataTable")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "Only passed queries from tests.", Scope = "member", Target = "~M:OSIsoft.PISystemDeploymentTests.PISqlClientTests.ExecuteNonQuery(System.String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA5359:Do Not Disable Certificate Validation", Justification = "Skipped due to Certificate Validation.", Scope = "member", Target = "~M:OSIsoft.PISystemDeploymentTests.PIWebAPIFixture.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA5359:Do Not Disable Certificate Validation", Justification = "Skipped due to Certificate Validation.", Scope = "member", Target = "~M:OSIsoft.PISystemDeploymentTests.ManualLoggerFixture.#ctor")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "Placeholder class for applying CollectionDefinitionAttribute and all the ICollectionFixture<> interfaces.", Scope = "type", Target = "~T:OSIsoft.PISystemDeploymentTests.AFFixture.AFTestCollection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "Placeholder class for applying CollectionDefinitionAttribute and all the ICollectionFixture<> interfaces.", Scope = "type", Target = "~T:OSIsoft.PISystemDeploymentTests.PIFixture.PITestCollection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "Used as base for creating other Urls.", Scope = "member", Target = "~P:OSIsoft.PISystemDeploymentTests.ManualLoggerFixture.HomePageUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "Used as base for creating other Urls.", Scope = "member", Target = "~P:OSIsoft.PISystemDeploymentTests.PIWebAPIFixture.HomePageUrl")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1806:Do not ignore method results", Justification = "Return value is not needed.", Scope = "member", Target = "~M:OSIsoft.PISystemDeploymentTests.DataLinkUtils.GetPIHOME(System.String@)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1812:Internal class that is apparently never instantiated", Justification = "Used with Json deserialization.", Scope = "member", Target = "~T:OSIsoft.PISystemDeploymentTests.AnnotationDescription")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1812:Internal class that is apparently never instantiated", Justification = "Used with Json deserialization.", Scope = "member", Target = "~T:OSIsoft.PISystemDeploymentTests.Subscribers")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1820:Test for empty strings using string length", Justification = "Need explicit check for empty string.", Scope = "member", Target = "~M:OSIsoft.PISystemDeploymentTests.AFFixture.DisplayAFValue(OSIsoft.AF.Asset.AFValue,System.Int32,System.Boolean)~System.String")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2234:Pass system uri objects instead of strings", Justification = "Not a full Uri.", Scope = "member", Target = "~M:OSIsoft.PISystemDeploymentTests.Vision3Tests.NewDisplayTestAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2234:Pass system uri objects instead of strings", Justification = "Not a full Uri.", Scope = "member", Target = "~M:OSIsoft.PISystemDeploymentTests.Vision3Fixture.FindOrCreateTestFolder~System.Threading.Tasks.Task{System.Net.Http.HttpResponseMessage}")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "Object is disposed because FindChangedPIPoints returns same cookie object.", Scope = "member", Target = "~M:OSIsoft.PISystemDeploymentTests.PIDAUpdatesTests.PointUpdatesTest")]
