trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/piwebapi_samples/R'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/piwebapi_samples/R'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projpath
    value: '/piwebapi_samples/R'
  - name: CredFile
    value: test_config.R
  - name: CredFileLibrary
    value: product-readiness.piwebapi_r.R
  - name: covStream
    value: PIWebAPIR
  - name: bdProject
    value: PIWebAPI_R

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - script: Rscript.exe run_tests.R
        workingDirectory: $(Build.SourcesDirectory)$(projpath)
        continueOnError: 'true'
        displayName: 'Run tests'

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**\output.xml'
          searchFolder: $(Build.SourcesDirectory)$(projpath)
          testRunTitle: 'Publish R test results'
        displayName: 'Publish test results'

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: r
