trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/piwebapi_samples/Data_Analysis'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/piwebapi_samples/Data_Analysis'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/piwebapi_samples/Data_Analysis/UploadUtility'
  - name: CredFile
    value: test_config.json
  - name: CredFileLibrary
    value: product-readiness.piweb_da.json
  - name: analysisProject
    value: PIWebAPI_Data_Analysis_Upload

jobs:
  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: dotnet
