jobs:
  - job: BinSkim
    pool:
      name: Hosted VS2017
    steps:
      - script: |
          dotnet restore
          dotnet msbuild -p:HIGHENTROPYVA=true
        workingDirectory: $(Build.SourcesDirectory)$(projPath)
        displayName: 'Build'

      - task: ms-codeanalysis.vss-microsoft-security-code-analysis-devops.build-task-binskim.BinSkim@3
        displayName: 'Analyze'
        inputs:
          AnalyzeTarget: '$(Build.SourcesDirectory)\*.dll;$(Build.SourcesDirectory)\*.exe'

      - task: ms-codeanalysis.vss-microsoft-security-code-analysis-devops.build-task-postanalysis.PostAnalysis@1
        displayName: 'Post Analysis'
        inputs:
          BinSkim: true
          BinSkimBreakOn: WarningAbove
