parameters:
  fileOriginal: ''
  fileLibrary: ''
  filePath: ''
  delete: false

steps:
  # Download Secure File
  # Download a secure file to a temporary location on the build or release agent
  - task: DownloadSecureFile@1
    inputs:
      secureFile: ${{ parameters.fileLibrary }}
    displayName: 'Download library config file'

  # Copy Files
  # Copy files from source folder to target folder using match patterns (The match patterns will only match file paths, not folder paths)
  - task: CopyFiles@2
    inputs:
      sourceFolder: $(Agent.TempDirectory)
      contents: ${{ parameters.fileLibrary }}
      targetFolder: $(Build.SourcesDirectory)${{ parameters.filePath }}/
      #cleanTargetFolder: false # Optional
      overWrite: true # Optional
      #flattenFolders: false # Optional
    displayName: 'Copy library config file'

  - bash: rm ${{ parameters.fileOriginal }}
    workingDirectory: $(Build.SourcesDirectory)${{ parameters.filePath }}/
    displayName: 'Delete original config file'
    condition: eq(${{ parameters.delete }}, true)

  - bash: mv ${{ parameters.fileLibrary }} ${{ parameters.fileOriginal }}
    workingDirectory: $(Build.SourcesDirectory)${{ parameters.filePath }}/
    displayName: 'Rename library config file'
